#!/bin/bash
# Concat log-files in the order of time-stamp

for file in "$@"; do
    head $file | grep "^\([0-9][0-9].\)\{5\}[0-9]\{3\}" | head -n1 | \
        awk '{print $1,$2,file}' file=$file | tee /tmp/$$
    test -z "$(cat /tmp/$$)" && \
        echo -e "\nWARNING: ignoring file '$file'\n" 1>&2
done | sort | awk '{print $3}' | xargs cat

